# Generated by Django 5.1.6 on 2025-03-01 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fotos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mifoto',
            name='imageurl',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
