# Generated by Django 5.1.6 on 2025-03-01 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True)),
                ('resumen', models.TextField(max_length=500)),
                ('detalle', models.TextField()),
                ('imagen_cover', models.ImageField(blank=True, null=True, upload_to='noticias/covers/')),
                ('imagen_estatica', models.ImageField(blank=True, null=True, upload_to='noticias/estaticas/')),
                ('imagen_dinamica', models.ImageField(blank=True, null=True, upload_to='noticias/dinamicas/')),
                ('publicada', models.BooleanField(default=True)),
            ],
        ),
    ]
