# Generated by Django 5.1.6 on 2025-03-01 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='fecha_publicacion',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='resumen',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='titulo',
            field=models.CharField(max_length=55),
        ),
    ]
